Debug deploy-in-swarm job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,6 +26,22 @@ jobs:
 #    needs: build-push-deploy
     runs-on: ubuntu-24.04
     steps:
+    - uses: appleboy/ssh-action@master      # Installing docker environment with docker swarm; creating project directory on server
+      with:
+        host: ${{ secrets.SERVER_HOST }}
+        username: ${{ secrets.SERVER_USERNAME }}
+        key: ${{ secrets.SERVER_SSH_KEY }}
+        passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
+        script: |
+          if ! [ -x "$(command -v docker)" ]; then
+            echo "Docker not found, installing..."
+            apt-get update
+            apt-get install -y docker.io docker-compose-plugin
+          fi           
+          if [ ! -d "${{ secrets.SERVER_PROJECT_PATH }}" ]; then
+            mkdir -p ${{ secrets.SERVER_PROJECT_PATH }}
+          fi
+          docker swarm init
     - uses: actions/checkout@v3
     - run: |
         mkdir -p ~/.ssh
@@ -37,10 +53,9 @@ jobs:
         export REPOSITORY_OWNER=${{ github.repository_owner}}
         export REGISTRY_HOST=ghcr.io/${REPOSITORY_OWNER,,}/${{ github.event.repository.name }}
         export CI_COMMIT_BRANCH=${{ github.ref_name }}
-        echo "variable REGISTRY_HOST=${REGISTRY_HOST}"
-        echo "variable CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}"
+        export SERVER_PROJECT_PATH=${{ secrets.SERVER_PROJECT_PATH }}
+    
         echo "${{ secrets.SERVER_AUTHORIZE_REGISRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
         docker context create remote-server --docker "host=ssh://${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}"
         docker context use remote-server 
-        docker compose -f ./docker/docker-compose-deploy.yaml config
         docker stack deploy --compose-file ./docker/docker-compose-deploy.yaml --with-registry-auth -d stack_my_app 
